# Generated by Django 4.1.5 on 2023-01-13 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=64)),
                ('movie_genre', models.CharField(max_length=32)),
                ('running_time', models.IntegerField()),
                ('review_content', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=128)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('movie_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
