# Generated by Django 4.1.5 on 2023-01-13 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie_created_at',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1700), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
