# Generated by Django 4.1.5 on 2023-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie_genre',
            field=models.CharField(choices=[('FA', 'Fantasy'), ('SF', 'Science Fiction'), ('HO', 'Horror'), ('CO', 'Comedy'), ('AC', 'Action'), ('CM', 'Classic Movie'), ('BL', 'Blockbuster'), ('TJ', 'Tear Jerker'), ('RC', 'RomCom'), ('RO', 'Romance'), ('WH', 'Whodunnit'), ('AN', 'Animation'), ('AM', 'Art Movie'), ('MD', 'Mock Documentary'), ('DO', 'Documentary'), ('DR', 'Drama'), ('DM', 'Disaster Movie')], max_length=2, null=True),
        ),
    ]
