# Generated by Django 4.1.5 on 2023-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie_genre',
            field=models.CharField(choices=[('RO', 'Romance'), ('CM', 'Classic Movie'), ('HO', 'Horror'), ('WH', 'Whodunnit'), ('RC', 'RomCom'), ('BL', 'Blockbuster'), ('SF', 'Science Fiction'), ('FA', 'Fantasy'), ('DR', 'Drama'), ('AN', 'Animation'), ('MD', 'Mock Documentary'), ('AM', 'Art Movie'), ('CO', 'Comedy'), ('AC', 'Action'), ('DM', 'Disaster Movie'), ('TJ', 'Tear Jerker'), ('DO', 'Documentary')], max_length=2, null=True),
        ),
    ]
